project: bstmain.o bstinsert.o preorder.o postorder.o inorder.o search.o bstdel.o
	gcc -g bstmain.o bstinsert.o preorder.o postorder.o inorder.o 
	search.o bstdel.o -o project

bstmain.o:bstmain.c
	gcc -c -g bstmain.c -o bstmain.o
bstinsert.o:bstinsert.c
	gcc -c -g bstinsert.c -o bstinsert.o
preorder.o:preorder.c
	gcc -c -g preorder.c -o preorder.o
postorder.o:postorder.c
	gcc -c -g postorder.c -o postorder.o
inorder.o:inorder.c
	gcc -c -g inorder.c -o inorder.o
search.o:search.c
	gcc -c -g search.c -o search.o
bstdel.o:bstdel.c
	gcc -c -g bstdel.c -o bstdel.o
